services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB} # Se leerá de un .env en el mismo nivel que docker-compose.yml
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Volume para persistencia de datos de PostgreSQL

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: # Esto hará que el contenedor lea el .env de la raíz del proyecto
      - .env
    depends_on:
      - db

volumes:
  pgdata: # Definición del volume